#!/usr/bin/python3
#
# Copyright (C) 2022 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; If not, see <http://www.gnu.org/licenses/>.

from anacondalib import VirtInstallMachineCase
from installer import Installer
from progress import Progress
from storage import Storage
from testlib import test_main  # pylint: disable=import-error
from utils import get_pretty_name


class TestInstallationProgress(VirtInstallMachineCase):

    def testBasic(self):
        # HACK Ignore some selinux errors
        self.allow_journal_messages(".*denied.*comm=\"tar\" name=\"/\".*")

        b = self.browser
        m = self.machine
        i = Installer(b, self.machine)
        p = Progress(b)
        _s = Storage(b, self.machine)  # noqa: F841

        i.open()

        i.reach(i.steps.REVIEW)
        i.begin_installation(needs_confirmation=False)

        with b.wait_timeout(300):
            b.wait_in_text("h2", "Installing")
            b.wait_in_text(".pf-v5-c-empty-state", "Storage configuration: Storage is currently being configured.")
            b.wait_in_text(".pf-v5-c-empty-state", "Software installation: Storage configuration complete. The "
                                                   "software is now being installed onto your device.")
            b.wait_in_text(".pf-v5-c-empty-state", "System configuration: Software installation complete. The system "
                                                   "is now being configured.")
            b.wait_in_text(".pf-v5-c-empty-state", "Finalizing: The system configuration is complete. Finalizing "
                                                   "installation may take a few moments.")

        p.wait_done()
        b.wait_in_text("h2", "Successfully installed")
        b.wait_in_text(".pf-v5-c-empty-state", f"To begin using {get_pretty_name(m)}, reboot your system")

        # Pixel test the complete progress step
        b.assert_pixels(
            "#app",
            "installation-progress-complete",
            ignore=[".logo", "#betanag-icon"],
        )

        # Check that at this stage 'Modify Storage' is not available
        b.click("#toggle-kebab")
        b.wait_visible("li.pf-m-aria-disabled #modify-storage")

        self.handleReboot()


if __name__ == '__main__':
    test_main()
