#!/usr/bin/python3
#
# Copyright (C) 2021 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; If not, see <http://www.gnu.org/licenses/>.

import datetime
from zoneinfo import ZoneInfo

from anacondalib import VirtInstallMachineCase
from installer import Installer
from language import Language
from testlib import nondestructive, test_main
from timezone import DateAndTime


@nondestructive
class TestDateAndTime(VirtInstallMachineCase):

    def setUp(self):
        super().setUp()
        self.allow_journal_messages("Error .* data: Connection reset by peer")

    def testDefaultState(self):
        """
        Description:
            Test default state picked up from backend

        Expected results:
            - WebUI auto date/time and timezone matches backend
            - NTP, timezone, date and time match backend
        """
        b = self.browser
        m = self.machine
        i = Installer(b, m)
        dt = DateAndTime(b, m)

        i.open()
        i.reach(i.steps.DATE_TIME)
        dt.check_auto_date_time(dt.dbus_get_ntp_enabled())
        dt.check_auto_timezone(True)
        ntp_servers = dt.dbus_get_ntp_servers()
        if ntp_servers:
            dt.check_ntp_server(ntp_servers[0])
        else:
            print("WARNING: No NTP servers returned from backend, skipping NTP check.")
        dt.check_timezone_label(dt.dbus_get_timezone())

    def testManualDateTime(self):
        """
        Description:
            Test manual entry of date and time.

        Expected results:
            - After disabling auto, manual values are applied to backend
        """
        b = self.browser
        m = self.machine
        i = Installer(b, m)
        lang = Language(b, m)
        dt = DateAndTime(b, m)

        i.open()
        lang.select_locale("de_DE")
        i.reach(i.steps.DATE_TIME)
        dt.set_auto_date_time(False)
        dt.set_date("2024-12-24")
        dt.check_date("2024-12-24")
        dt.set_time("18:30")
        dt.check_time("18:30")
        self.assertIn("2024-12-24T18:30", dt.dbus_get_system_datetime())

    def testNtpServerSelection(self):
        """
        Description:
            Test selecting another NTP server.

        Expected results:
            - Selected server is shown and set on backend
        """
        b = self.browser
        m = self.machine
        i = Installer(b, m)
        dt = DateAndTime(b, m)

        i.open()
        i.reach(i.steps.DATE_TIME)
        dt.select_ntp_server("time.cloudflare.com")
        dt.check_ntp_server("time.cloudflare.com")

    def testManualTimezone(self):
        """
        Description:
            Test manual timezone selection.

        Expected results:
            - Manual region/city changes backend timezone
        """
        b = self.browser
        m = self.machine
        i = Installer(b, m)
        dt = DateAndTime(b, m)

        i.open()
        i.reach(i.steps.DATE_TIME)
        dt.set_auto_timezone(False)
        dt.select_region("Europe")
        dt.select_city("Prague")
        dt.check_timezone_label("Europe/Prague")
        self.assertEqual(dt.dbus_get_timezone(), "Europe/Prague")

    def testTimeFormatSwitch(self):
        """
        Description:
            Test switching time format.

        Expected results:
            - Time field display switches between 24h and AM/PM
        """
        b = self.browser
        m = self.machine
        i = Installer(b, m)
        dt = DateAndTime(b, m)

        i.open()
        i.reach(i.steps.DATE_TIME)
        dt.set_time_format("ampm")
        dt.check_time_format("ampm")
        dt.set_time_format("24")
        dt.check_time_format("24")

    def testTimezoneAndTimeformat(self):
        """
        Test full cycle of timezone, time format (24/ampm) and correct UTC backend saving.
        """
        b = self.browser
        m = self.machine
        i = Installer(b, m)
        dt = DateAndTime(b, m)

        i.open()
        i.reach(i.steps.DATE_TIME)
        dt.set_auto_date_time(False)
        dt.set_auto_timezone(False)

        dt.set_time_format("24")
        dt.check_time_format("24")
        dt.select_region("America")
        dt.select_city("New_York")
        dt.check_timezone_label("America/New_York")
        self.assertEqual(dt.dbus_get_timezone(), "America/New_York")

        dt.set_date("2025-01-31")
        dt.set_time("15:45")

        dt.set_time_format("ampm")
        dt.check_time_format("ampm")
        dt.check_time("03:45 PM")

        dt.set_time_format("24")
        dt.check_time_format("24")
        dt.check_time("15:45")

        backend_iso = dt.dbus_get_system_datetime()
        dt_parsed = datetime.datetime.fromisoformat(backend_iso)
        dt_utc = dt_parsed.astimezone(datetime.timezone.utc)

        expected_utc = datetime.datetime(2025, 1, 31, 20, 45, tzinfo=datetime.timezone.utc)
        assert dt_utc.strftime("%Y-%m-%dT%H:%M") == expected_utc.strftime("%Y-%m-%dT%H:%M")

        dt.select_region("Asia")
        dt.select_city("Tokyo")
        dt.check_timezone_label("Asia/Tokyo")

        dt.check_time("05:45")
        dt.set_time("00:45")

        dt.set_time_format("ampm")
        dt.check_time_format("ampm")
        dt.check_time("12:45 AM")

        dt.set_time_format("24")
        dt.check_time_format("24")
        dt.set_time("08:00")

        local_tokyo = datetime.datetime(2025, 2, 1, 8, 0, tzinfo=ZoneInfo("Asia/Tokyo"))
        backend_iso3 = dt.dbus_get_system_datetime()
        self.assertTrue(
            backend_iso3.startswith(local_tokyo.strftime("%Y-%m-%dT%H:%M")),
            f"Expected backend local time {local_tokyo}, got {backend_iso3}"
        )


if __name__ == '__main__':
    test_main()
