#!/usr/bin/python3
#
# Copyright (C) 2024 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; If not, see <http://www.gnu.org/licenses/>.

from anacondalib import VirtInstallMachineCase, test_plan
from installer import Installer
from operating_systems import WindowsOS
from progress import Progress
from review import Review
from storage import Storage, StorageUtils
from testlib import nondestructive, test_main  # pylint: disable=import-error
from utils import get_pretty_name


@nondestructive
class TestExistingSystemFedora(VirtInstallMachineCase):
    disk_image = "fedora-rawhide"

    def testScenarioEraseAll(self):
        b = self.browser
        m = self.machine

        i = Installer(b, m)
        r = Review(b, m)

        i.open()
        i.reach(i.steps.REVIEW)

        for device in ["vda1", "vda2", "vda3", "vda4"]:
            r.check_disk_row("vda", parent=device, action="delete")

        r.check_deleted_system("Fedora Linux")

class _TestFedoraPlansUseFreeSpace(VirtInstallMachineCase):
    """
    Test Fedora plans: https://fedoraproject.org/wiki/Test_Results:Current_Installation_Test

    These tests are based on the Fedora QA test plans for installation.

    All tests below are destructive as they complete the installation process.
    """

    disk_image = "debian-stable"
    disk_size = 20

    def install(self, needs_confirmation):
        b = self.browser
        m = self.machine

        i = Installer(b, m)
        p = Progress(b)

        i.begin_installation(button_text="Install", needs_confirmation=needs_confirmation)
        with b.wait_timeout(300):
            p.wait_done()

        # FIXME: https://bugzilla.redhat.com/show_bug.cgi?id=2325707
        # This should be removed from the test
        if self.efi:
            # Add efibootmgr entry for the second OS
            distro_name = self.disk_image.split("-")[0]
            m.execute(f"efibootmgr -c -d /dev/vda -p 15 -L {distro_name} -l '/EFI/{distro_name}/shimx64.efi'")
            # Select the Fedora grub entry for first boot
            m.execute("efibootmgr -n 0001")

        self.handleReboot()

    def verifyDualBoot(self, root_one_size=None, root_two_size=None):
        b = self.browser
        m = self.machine
        s = StorageUtils(b, m)

        # Expect the new OS is the default grub entry
        pretty_name = get_pretty_name(m)
        self.assertIn("Fedora Linux", pretty_name)

        # Check that the expected partition layout is created on the selected device
        lsblk = s.get_lsblk_json()
        block_devs = lsblk["blockdevices"]
        vda = next(dev for dev in block_devs if dev["name"] == "vda")

        vda2 = next(part for part in vda["children"] if part["name"] == "vda2")
        self.assertEqual(vda2["mountpoints"], ["/boot"])

        vda3 = next(part for part in vda["children"] if part["name"] == "vda3")
        vda3_root = next(part for part in vda3["children"] if "/" in part["mountpoints"])
        self.assertEqual(vda3_root["size"], str(root_one_size) + "G")

        # Select second OS grub entry
        self.selectBootMenuEntry(2)
        m.reboot()
        pretty_name = get_pretty_name(m)
        self.assertIn("Debian GNU/Linux", pretty_name)

        # Check that the pre-existing partitions are still present
        lsblk = s.get_lsblk_json()
        block_devs = lsblk["blockdevices"]
        vda = next(dev for dev in block_devs if dev["name"] == "vda")

        vda1 = next(part for part in vda["children"] if part["name"] == "vda1")
        self.assertEqual(vda1["mountpoints"], ["/"])
        self.assertEqual(vda1["size"], str(root_two_size) + "G")

        vda15 = next(part for part in vda["children"] if part["name"] == "vda15")
        # TODO: add explanation why the /efi mountpoint is present when legacy boot is used
        if self.efi:
            self.assertEqual(vda15["mountpoints"], ["/boot/efi"])
        else:
            self.assertEqual(vda15["mountpoints"], ["/efi", "/boot/efi"])

    @test_plan("https://fedoraproject.org/wiki/QA:Testcase_partitioning_guided_free_space")
    def testScenarioUseFreeSpace(self):
        b = self.browser
        m = self.machine
        i = Installer(b, m)
        r = Review(b, m)
        s = Storage(b, m)

        i.open()
        i.reach(i.steps.INSTALLATION_METHOD)
        s.set_partitioning("use-free-space")
        i.next()
        s.check_encryption_selected(False)
        i.reach(i.steps.REVIEW)
        r.check_checkbox_not_present()

        self.install(needs_confirmation=False)
        self.verifyDualBoot(root_one_size=9, root_two_size=9.9)

    @test_plan("https://fedoraproject.org/wiki/QA:Testcase_partitioning_guided_shrink")
    def testReclaimSpaceShrink(self):
        b = self.browser
        m = self.machine
        i = Installer(b, m)
        r = Review(b, m)
        s = Storage(b, m)

        i.open()
        i.reach(i.steps.INSTALLATION_METHOD)
        s.set_partitioning("use-free-space")
        s.reclaim_set_checkbox(True)
        i.next(True)

        s.reclaim_shrink_device("vda1", "5", rowIndex=3)
        s.reclaim_modal_submit()

        i.reach(i.steps.REVIEW)
        r.check_some_resized_checkbox_label()
        r.check_disk_row("vda", parent="vda1", size="5.00 GB", action="resized from 10.6 GB")
        r.check_resized_system("Debian", ["vda1"])

        self.install(needs_confirmation=True)
        self.verifyDualBoot(root_one_size=14.2, root_two_size=4.7)

class TestFedoraPlansUseFreeSpaceBIOS(_TestFedoraPlansUseFreeSpace):
    efi = False

class TestFedoraPlansUseFreeSpaceUEFI(_TestFedoraPlansUseFreeSpace):
    efi = True

@nondestructive
class TestExistingSystemWindows(VirtInstallMachineCase):
    disk_size = 20

    def setUp(self):
        super().setUp()
        WindowsOS(machine=self.machine, browser=self.browser).partition_disk()

    def testScenarioEraseAll(self):
        b = self.browser
        m = self.machine
        i = Installer(b, m)
        r = Review(b, m)

        i.open()
        i.reach(i.steps.REVIEW)

        for device in ["vda1", "vda2", "vda3", "vda4"]:
            r.check_disk_row("vda", parent=device, action="delete")

        r.check_all_erased_checkbox_label()
        r.check_deleted_system("Windows")


class TestExistingSystemUbuntu(VirtInstallMachineCase):
    disk_image = "ubuntu-stable"

    @nondestructive
    def testReclaimSpaceShrink(self):
        b = self.browser
        m = self.machine
        i = Installer(b, m)
        s = Storage(b, m)
        r = Review(b, m)

        i.open()
        i.reach(i.steps.INSTALLATION_METHOD)
        s.set_partitioning("use-free-space")
        s.reclaim_set_checkbox(True)
        i.next(True)

        s.reclaim_shrink_device("vda1", "7", rowIndex=3)
        s.reclaim_modal_submit()

        i.reach(i.steps.REVIEW)
        # Don't specify the exact original size as this might change with image refreshes
        r.check_disk_row("vda", parent="vda1", size="7.00 GB", action="resized from")
        r.check_resized_system("Ubuntu", ["vda1"])


if __name__ == '__main__':
    test_main()
