#!/usr/bin/python3
#
# Copyright (C) 2025 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; If not, see <http://www.gnu.org/licenses/>.

from anacondalib import VirtInstallMachineCase
from installer import Installer
from network import SYSROOT_PATH, WIRED_CONNECTION_NAME, Network, remove_anaconda_default_connections
from progress import Progress
from testlib import nondestructive, test_main  # pylint: disable=import-error
from utils import pretend_live_workstation_iso


class TestNetwork(VirtInstallMachineCase):

    def setUp(self):
        super().setUp()
        # FIXME WORKAROUND
        remove_anaconda_default_connections(self.machine)

    @nondestructive
    def testHidenOnLiveISO(self):
        """
        Description:
            Test that the network configuration is not accessible on Live ISO

        Expected results:
            - The UI elements for accessing network configuration are not present
        """
        b = self.browser
        m = self.machine
        i = Installer(b, m)
        n = Network(b, m)

        pretend_live_workstation_iso(self, i, m)

        i.open()

        n.check_no_network_ui()

    def testConnectionsPreInstall(self):
        """
        Description:
            Test network configuration modifies profiles correctly.
            A pre-installation phase variant - a shorter test assuming the connections
            will be passed to the system correctly at the end of installation.

        Expected results:
            - Expected connection profiles in installer with expected values
            - Network configuration modifies correct profiles
        """
        b = self.browser
        m = self.machine
        i = Installer(b, m)
        n = Network(b, m)

        i.open()

        iface = n.get_the_iface()
        def_con_name = WIRED_CONNECTION_NAME
        n.preinstall_connection_test(i, iface, def_con_name)

    def testConnections(self):
        """
        Description:
            Test network configuration modifies profiles correctly.

        Expected results:
            - Expected connection profiles in installer with expected values
            - Network configuration modifies correct profiles
        """
        b = self.browser
        m = self.machine
        i = Installer(b, m)
        n = Network(b, m)

        i.open()

        iface = n.get_the_iface()
        def_con_name = WIRED_CONNECTION_NAME
        n.preinstall_connection_test(i, iface, def_con_name)

        i.begin_installation(needs_confirmation=False)
        p = Progress(b)
        p.wait_done()

        # Check profiles in installed system
        n.check_con_profile_files(def_con_name, 1, root=SYSROOT_PATH, file_name=def_con_name)
        # Check there is only single persistent profile
        # FIXME WORKAROUND
        #n.check_con_profile_files("", 2, root=SYSROOT_PATH)
        n.check_con_profile_files("", 1, root=SYSROOT_PATH)


if __name__ == '__main__':
    test_main()
