#!/usr/bin/python3
#
# Copyright (C) 2025 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; If not, see <http://www.gnu.org/licenses/>.

from anacondalib import VirtInstallMachineCase
from installer import Installer
from network import SYSROOT_PATH, WIRED_CONNECTION_NAME, Network, remove_anaconda_default_connections
from progress import Progress
from testlib import test_main  # pylint: disable=import-error


class TestNetwork_E2E(VirtInstallMachineCase):

    def setUp(self):
        super().setUp()
        # FIXME WORKAROUND - remove anaconda default connection profiles
        remove_anaconda_default_connections(self.machine)

    def testConnectionsE2E(self):
        """
        Description:
            Test network configuration modifies profiles correctly.

        Expected results:
            - Expected connection profiles in installer with expected values
            - Network configuration modifies correct profiles
            - Test that the booted system has expected network configuration
        """
        b = self.browser
        m = self.machine
        i = Installer(b, m)
        n = Network(b, m)

        i.open()

        iface = n.get_the_iface()
        def_con_name = WIRED_CONNECTION_NAME
        n.preinstall_connection_test(i, iface, def_con_name)

        i.begin_installation(needs_confirmation=False)
        p = Progress(b)
        p.wait_done()

        # Check profiles in installed system
        n.check_con_profile_files(def_con_name, 1, root=SYSROOT_PATH, file_name=def_con_name)
        # Check there is only single persistent profile
        # FIXME WORKAROUND
        #n.check_con_profile_files("", 2, root=SYSROOT_PATH)
        n.check_con_profile_files("", 1, root=SYSROOT_PATH)

        self.handleReboot()

        # Check profiles in installed system
        n.check_con_profile_files(def_con_name, 1, file_name=def_con_name)
        # Check there is only single persistent profile
        # FIXME WORKAROUND
        #n.check_con_profile_files("", 2)
        n.check_con_profile_files("", 1)

        # FIXME WORKAROUND
        # Sometimes iface gets priority over def_con_name
        #n.check_iface_state(iface, "GENERAL.CONNECTION", iface)
        n.check_iface_state(iface, "GENERAL.CONNECTION", def_con_name)


if __name__ == '__main__':
    test_main()
