#!/usr/bin/python3
#
# Copyright (C) 2026 Red Hat, Inc.
# SPDX-License-Identifier: LGPL-2.1-or-later

from anacondalib import VirtInstallMachineCase
from installer import Installer
from network import SYSROOT_PATH, WIRED_CONNECTION_NAME, Network
from progress import Progress
from testlib import test_main  # pylint: disable=import-error


class TestNetwork_E2E(VirtInstallMachineCase):

    def testConnectionsE2E(self):
        """
        Description:
            Test network configuration modifies profiles correctly.

        Expected results:
            - Expected connection profiles in installer with expected values
            - Network configuration modifies correct profiles
            - Test that the booted system has expected network configuration
        """
        b = self.browser
        m = self.machine
        i = Installer(b, m)
        n = Network(b, m)

        i.open()

        iface = n.get_the_iface()
        con_name = WIRED_CONNECTION_NAME
        n.preinstall_connection_test(i, iface, con_name)

        mtu_value = "1600"
        n.set_mtu_on_iface(iface, mtu_value)

        n.check_con_settings([
            [con_name, "802-3-ethernet.mtu", mtu_value, None],
        ])

        i.begin_installation(needs_confirmation=False)
        p = Progress(b)
        p.wait_done()

        # Check profiles in installed system
        n.check_con_profile_files(con_name, 1, root=SYSROOT_PATH, file_name=con_name)
        # Check there is only single persistent profile
        n.check_con_profile_files("", 1, root=SYSROOT_PATH)

        n.check_con_settings([
            [con_name, "802-3-ethernet.mtu", mtu_value, None],
        ])

        self.handleReboot()

        # Check profiles in installed system
        n.check_con_profile_files(con_name, 1, file_name=con_name)
        # Check there is only single persistent profile
        n.check_con_profile_files("", 1)

        n.check_iface_state(iface, "GENERAL.CONNECTION", con_name)

        n.check_con_settings([
            [con_name, "802-3-ethernet.mtu", mtu_value, None],
        ])


if __name__ == '__main__':
    test_main()
