#!/bin/bash

set -eu

# build the anaconda-webui rpm && download anaconda-webui missing dependencies
make srpm
test/build-rpms -v anaconda-webui*.src.rpm

# makeupdates must be run from the top level of the anaconda source tree
# shellcheck disable=SC2086,SC2046
scripts/makeupdates --add tmp/rpms/*.rpm
